/*
 * This file is generated by jOOQ.
 */
package com.dasad.empresa.jooq.model.tables;


import com.dasad.empresa.jooq.model.Keys;
import com.dasad.empresa.jooq.model.Public;
import com.dasad.empresa.jooq.model.tables.Subcategoria.SubcategoriaPath;
import com.dasad.empresa.jooq.model.tables.Usuario.UsuarioPath;
import com.dasad.empresa.jooq.model.tables.records.UsuarioSubcategoriaRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsuarioSubcategoria extends TableImpl<UsuarioSubcategoriaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.usuario_subcategoria</code>
     */
    public static final UsuarioSubcategoria USUARIO_SUBCATEGORIA = new UsuarioSubcategoria();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UsuarioSubcategoriaRecord> getRecordType() {
        return UsuarioSubcategoriaRecord.class;
    }

    /**
     * The column <code>public.usuario_subcategoria.usuario_id</code>.
     */
    public final TableField<UsuarioSubcategoriaRecord, Integer> USUARIO_ID = createField(DSL.name("usuario_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.usuario_subcategoria.subcategoria_id</code>.
     */
    public final TableField<UsuarioSubcategoriaRecord, Integer> SUBCATEGORIA_ID = createField(DSL.name("subcategoria_id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.usuario_subcategoria.data_criacao</code>.
     */
    public final TableField<UsuarioSubcategoriaRecord, LocalDateTime> DATA_CRIACAO = createField(DSL.name("data_criacao"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.usuario_subcategoria.data_exclusao</code>.
     */
    public final TableField<UsuarioSubcategoriaRecord, LocalDateTime> DATA_EXCLUSAO = createField(DSL.name("data_exclusao"), SQLDataType.LOCALDATETIME(6), this, "");

    private UsuarioSubcategoria(Name alias, Table<UsuarioSubcategoriaRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UsuarioSubcategoria(Name alias, Table<UsuarioSubcategoriaRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.usuario_subcategoria</code> table
     * reference
     */
    public UsuarioSubcategoria(String alias) {
        this(DSL.name(alias), USUARIO_SUBCATEGORIA);
    }

    /**
     * Create an aliased <code>public.usuario_subcategoria</code> table
     * reference
     */
    public UsuarioSubcategoria(Name alias) {
        this(alias, USUARIO_SUBCATEGORIA);
    }

    /**
     * Create a <code>public.usuario_subcategoria</code> table reference
     */
    public UsuarioSubcategoria() {
        this(DSL.name("usuario_subcategoria"), null);
    }

    public <O extends Record> UsuarioSubcategoria(Table<O> path, ForeignKey<O, UsuarioSubcategoriaRecord> childPath, InverseForeignKey<O, UsuarioSubcategoriaRecord> parentPath) {
        super(path, childPath, parentPath, USUARIO_SUBCATEGORIA);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class UsuarioSubcategoriaPath extends UsuarioSubcategoria implements Path<UsuarioSubcategoriaRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> UsuarioSubcategoriaPath(Table<O> path, ForeignKey<O, UsuarioSubcategoriaRecord> childPath, InverseForeignKey<O, UsuarioSubcategoriaRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private UsuarioSubcategoriaPath(Name alias, Table<UsuarioSubcategoriaRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public UsuarioSubcategoriaPath as(String alias) {
            return new UsuarioSubcategoriaPath(DSL.name(alias), this);
        }

        @Override
        public UsuarioSubcategoriaPath as(Name alias) {
            return new UsuarioSubcategoriaPath(alias, this);
        }

        @Override
        public UsuarioSubcategoriaPath as(Table<?> alias) {
            return new UsuarioSubcategoriaPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<UsuarioSubcategoriaRecord> getPrimaryKey() {
        return Keys.USUARIO_SUBCATEGORIA_PKEY;
    }

    @Override
    public List<ForeignKey<UsuarioSubcategoriaRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USUARIO_SUBCATEGORIA__USUARIO_SUBCATEGORIA_SUBCATEGORIA_ID_FKEY, Keys.USUARIO_SUBCATEGORIA__USUARIO_SUBCATEGORIA_USUARIO_ID_FKEY);
    }

    private transient SubcategoriaPath _subcategoria;

    /**
     * Get the implicit join path to the <code>public.subcategoria</code> table.
     */
    public SubcategoriaPath subcategoria() {
        if (_subcategoria == null)
            _subcategoria = new SubcategoriaPath(this, Keys.USUARIO_SUBCATEGORIA__USUARIO_SUBCATEGORIA_SUBCATEGORIA_ID_FKEY, null);

        return _subcategoria;
    }

    private transient UsuarioPath _usuario;

    /**
     * Get the implicit join path to the <code>public.usuario</code> table.
     */
    public UsuarioPath usuario() {
        if (_usuario == null)
            _usuario = new UsuarioPath(this, Keys.USUARIO_SUBCATEGORIA__USUARIO_SUBCATEGORIA_USUARIO_ID_FKEY, null);

        return _usuario;
    }

    @Override
    public UsuarioSubcategoria as(String alias) {
        return new UsuarioSubcategoria(DSL.name(alias), this);
    }

    @Override
    public UsuarioSubcategoria as(Name alias) {
        return new UsuarioSubcategoria(alias, this);
    }

    @Override
    public UsuarioSubcategoria as(Table<?> alias) {
        return new UsuarioSubcategoria(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UsuarioSubcategoria rename(String name) {
        return new UsuarioSubcategoria(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UsuarioSubcategoria rename(Name name) {
        return new UsuarioSubcategoria(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UsuarioSubcategoria rename(Table<?> name) {
        return new UsuarioSubcategoria(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UsuarioSubcategoria where(Condition condition) {
        return new UsuarioSubcategoria(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UsuarioSubcategoria where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UsuarioSubcategoria where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UsuarioSubcategoria where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UsuarioSubcategoria where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UsuarioSubcategoria where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UsuarioSubcategoria where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UsuarioSubcategoria where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UsuarioSubcategoria whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UsuarioSubcategoria whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
