/*
 * This file is generated by jOOQ.
 */
package com.dasad.empresa.jooq.model.tables.records;


import com.dasad.empresa.jooq.model.tables.UsuarioFoto;

import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsuarioFotoRecord extends UpdatableRecordImpl<UsuarioFotoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.usuario_foto.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.usuario_foto.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.usuario_foto.usuario_id</code>.
     */
    public void setUsuarioId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.usuario_foto.usuario_id</code>.
     */
    public Integer getUsuarioId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.usuario_foto.foto</code>.
     */
    public void setFoto(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.usuario_foto.foto</code>.
     */
    public byte[] getFoto() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>public.usuario_foto.data_criacao</code>.
     */
    public void setDataCriacao(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.usuario_foto.data_criacao</code>.
     */
    public LocalDateTime getDataCriacao() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.usuario_foto.data_atualizacao</code>.
     */
    public void setDataAtualizacao(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.usuario_foto.data_atualizacao</code>.
     */
    public LocalDateTime getDataAtualizacao() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.usuario_foto.ativo</code>.
     */
    public void setAtivo(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.usuario_foto.ativo</code>.
     */
    public Boolean getAtivo() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsuarioFotoRecord
     */
    public UsuarioFotoRecord() {
        super(UsuarioFoto.USUARIO_FOTO);
    }

    /**
     * Create a detached, initialised UsuarioFotoRecord
     */
    public UsuarioFotoRecord(Integer id, Integer usuarioId, byte[] foto, LocalDateTime dataCriacao, LocalDateTime dataAtualizacao, Boolean ativo) {
        super(UsuarioFoto.USUARIO_FOTO);

        setId(id);
        setUsuarioId(usuarioId);
        setFoto(foto);
        setDataCriacao(dataCriacao);
        setDataAtualizacao(dataAtualizacao);
        setAtivo(ativo);
        resetTouchedOnNotNull();
    }
}
