/*
 * This file is generated by jOOQ.
 */
package com.dasad.empresa.jooq.model.tables.records;


import com.dasad.empresa.jooq.model.tables.UsuarioOrganizacao;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsuarioOrganizacaoRecord extends UpdatableRecordImpl<UsuarioOrganizacaoRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.usuario_organizacao.usuario_id</code>.
     */
    public void setUsuarioId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.usuario_organizacao.usuario_id</code>.
     */
    public Integer getUsuarioId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.usuario_organizacao.organizacao_id</code>.
     */
    public void setOrganizacaoId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.usuario_organizacao.organizacao_id</code>.
     */
    public Integer getOrganizacaoId() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsuarioOrganizacaoRecord
     */
    public UsuarioOrganizacaoRecord() {
        super(UsuarioOrganizacao.USUARIO_ORGANIZACAO);
    }

    /**
     * Create a detached, initialised UsuarioOrganizacaoRecord
     */
    public UsuarioOrganizacaoRecord(Integer usuarioId, Integer organizacaoId) {
        super(UsuarioOrganizacao.USUARIO_ORGANIZACAO);

        setUsuarioId(usuarioId);
        setOrganizacaoId(organizacaoId);
        resetTouchedOnNotNull();
    }
}
