/*
 * This file is generated by jOOQ.
 */
package com.dasad.empresa.jooq.model.tables.records;


import com.dasad.empresa.jooq.model.tables.UsuarioSubcategoria;

import java.time.LocalDateTime;

import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsuarioSubcategoriaRecord extends UpdatableRecordImpl<UsuarioSubcategoriaRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.usuario_subcategoria.usuario_id</code>.
     */
    public void setUsuarioId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.usuario_subcategoria.usuario_id</code>.
     */
    public Integer getUsuarioId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.usuario_subcategoria.subcategoria_id</code>.
     */
    public void setSubcategoriaId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.usuario_subcategoria.subcategoria_id</code>.
     */
    public Integer getSubcategoriaId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.usuario_subcategoria.data_criacao</code>.
     */
    public void setDataCriacao(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.usuario_subcategoria.data_criacao</code>.
     */
    public LocalDateTime getDataCriacao() {
        return (LocalDateTime) get(2);
    }

    /**
     * Setter for <code>public.usuario_subcategoria.data_exclusao</code>.
     */
    public void setDataExclusao(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.usuario_subcategoria.data_exclusao</code>.
     */
    public LocalDateTime getDataExclusao() {
        return (LocalDateTime) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsuarioSubcategoriaRecord
     */
    public UsuarioSubcategoriaRecord() {
        super(UsuarioSubcategoria.USUARIO_SUBCATEGORIA);
    }

    /**
     * Create a detached, initialised UsuarioSubcategoriaRecord
     */
    public UsuarioSubcategoriaRecord(Integer usuarioId, Integer subcategoriaId, LocalDateTime dataCriacao, LocalDateTime dataExclusao) {
        super(UsuarioSubcategoria.USUARIO_SUBCATEGORIA);

        setUsuarioId(usuarioId);
        setSubcategoriaId(subcategoriaId);
        setDataCriacao(dataCriacao);
        setDataExclusao(dataExclusao);
        resetTouchedOnNotNull();
    }
}
