/*
 * This file is generated by jOOQ.
 */
package com.dasad.empresa.jooq.model;


import com.dasad.empresa.jooq.model.tables.Categoria;
import com.dasad.empresa.jooq.model.tables.CategoriaEquipamentos;
import com.dasad.empresa.jooq.model.tables.Cidade;
import com.dasad.empresa.jooq.model.tables.Cliente;
import com.dasad.empresa.jooq.model.tables.Desconto;
import com.dasad.empresa.jooq.model.tables.Endereco;
import com.dasad.empresa.jooq.model.tables.Estado;
import com.dasad.empresa.jooq.model.tables.Estoque;
import com.dasad.empresa.jooq.model.tables.Fornecedor;
import com.dasad.empresa.jooq.model.tables.HistoricoPreco;
import com.dasad.empresa.jooq.model.tables.ItemPedido;
import com.dasad.empresa.jooq.model.tables.Organizacao;
import com.dasad.empresa.jooq.model.tables.Pais;
import com.dasad.empresa.jooq.model.tables.PasswordResetToken;
import com.dasad.empresa.jooq.model.tables.Pedido;
import com.dasad.empresa.jooq.model.tables.Perfil;
import com.dasad.empresa.jooq.model.tables.PrecosRegionais;
import com.dasad.empresa.jooq.model.tables.Produto;
import com.dasad.empresa.jooq.model.tables.ProdutoFornecedor;
import com.dasad.empresa.jooq.model.tables.Regioes;
import com.dasad.empresa.jooq.model.tables.Subcategoria;
import com.dasad.empresa.jooq.model.tables.Usuario;
import com.dasad.empresa.jooq.model.tables.UsuarioFoto;
import com.dasad.empresa.jooq.model.tables.UsuarioOrganizacao;
import com.dasad.empresa.jooq.model.tables.UsuarioPerfil;
import com.dasad.empresa.jooq.model.tables.UsuarioRecuperarSenha;
import com.dasad.empresa.jooq.model.tables.UsuarioSubcategoria;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * standard public schema
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * Tabela principal de categorias de serviços
     */
    public final Categoria CATEGORIA = Categoria.CATEGORIA;

    /**
     * Equipamentos necessários para cada categoria de serviço
     */
    public final CategoriaEquipamentos CATEGORIA_EQUIPAMENTOS = CategoriaEquipamentos.CATEGORIA_EQUIPAMENTOS;

    /**
     * The table <code>public.cidade</code>.
     */
    public final Cidade CIDADE = Cidade.CIDADE;

    /**
     * The table <code>public.cliente</code>.
     */
    public final Cliente CLIENTE = Cliente.CLIENTE;

    /**
     * The table <code>public.desconto</code>.
     */
    public final Desconto DESCONTO = Desconto.DESCONTO;

    /**
     * The table <code>public.endereco</code>.
     */
    public final Endereco ENDERECO = Endereco.ENDERECO;

    /**
     * The table <code>public.estado</code>.
     */
    public final Estado ESTADO = Estado.ESTADO;

    /**
     * The table <code>public.estoque</code>.
     */
    public final Estoque ESTOQUE = Estoque.ESTOQUE;

    /**
     * The table <code>public.fornecedor</code>.
     */
    public final Fornecedor FORNECEDOR = Fornecedor.FORNECEDOR;

    /**
     * The table <code>public.historico_preco</code>.
     */
    public final HistoricoPreco HISTORICO_PRECO = HistoricoPreco.HISTORICO_PRECO;

    /**
     * The table <code>public.item_pedido</code>.
     */
    public final ItemPedido ITEM_PEDIDO = ItemPedido.ITEM_PEDIDO;

    /**
     * The table <code>public.organizacao</code>.
     */
    public final Organizacao ORGANIZACAO = Organizacao.ORGANIZACAO;

    /**
     * The table <code>public.pais</code>.
     */
    public final Pais PAIS = Pais.PAIS;

    /**
     * The table <code>public.password_reset_token</code>.
     */
    public final PasswordResetToken PASSWORD_RESET_TOKEN = PasswordResetToken.PASSWORD_RESET_TOKEN;

    /**
     * The table <code>public.pedido</code>.
     */
    public final Pedido PEDIDO = Pedido.PEDIDO;

    /**
     * The table <code>public.perfil</code>.
     */
    public final Perfil PERFIL = Perfil.PERFIL;

    /**
     * Preços diferenciados por região para cada subcategoria
     */
    public final PrecosRegionais PRECOS_REGIONAIS = PrecosRegionais.PRECOS_REGIONAIS;

    /**
     * The table <code>public.produto</code>.
     */
    public final Produto PRODUTO = Produto.PRODUTO;

    /**
     * The table <code>public.produto_fornecedor</code>.
     */
    public final ProdutoFornecedor PRODUTO_FORNECEDOR = ProdutoFornecedor.PRODUTO_FORNECEDOR;

    /**
     * Regiões de atuação dos prestadores de serviço
     */
    public final Regioes REGIOES = Regioes.REGIOES;

    /**
     * Tabela de subcategorias de serviços vinculadas às categorias
     */
    public final Subcategoria SUBCATEGORIA = Subcategoria.SUBCATEGORIA;

    /**
     * The table <code>public.usuario</code>.
     */
    public final Usuario USUARIO = Usuario.USUARIO;

    /**
     * The table <code>public.usuario_foto</code>.
     */
    public final UsuarioFoto USUARIO_FOTO = UsuarioFoto.USUARIO_FOTO;

    /**
     * The table <code>public.usuario_organizacao</code>.
     */
    public final UsuarioOrganizacao USUARIO_ORGANIZACAO = UsuarioOrganizacao.USUARIO_ORGANIZACAO;

    /**
     * The table <code>public.usuario_perfil</code>.
     */
    public final UsuarioPerfil USUARIO_PERFIL = UsuarioPerfil.USUARIO_PERFIL;

    /**
     * The table <code>public.usuario_recuperar_senha</code>.
     */
    public final UsuarioRecuperarSenha USUARIO_RECUPERAR_SENHA = UsuarioRecuperarSenha.USUARIO_RECUPERAR_SENHA;

    /**
     * The table <code>public.usuario_subcategoria</code>.
     */
    public final UsuarioSubcategoria USUARIO_SUBCATEGORIA = UsuarioSubcategoria.USUARIO_SUBCATEGORIA;

    /**
     * No further instances allowed
     */
    private Public() {
        super(DSL.name("public"), null, DSL.comment("standard public schema"));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Categoria.CATEGORIA,
            CategoriaEquipamentos.CATEGORIA_EQUIPAMENTOS,
            Cidade.CIDADE,
            Cliente.CLIENTE,
            Desconto.DESCONTO,
            Endereco.ENDERECO,
            Estado.ESTADO,
            Estoque.ESTOQUE,
            Fornecedor.FORNECEDOR,
            HistoricoPreco.HISTORICO_PRECO,
            ItemPedido.ITEM_PEDIDO,
            Organizacao.ORGANIZACAO,
            Pais.PAIS,
            PasswordResetToken.PASSWORD_RESET_TOKEN,
            Pedido.PEDIDO,
            Perfil.PERFIL,
            PrecosRegionais.PRECOS_REGIONAIS,
            Produto.PRODUTO,
            ProdutoFornecedor.PRODUTO_FORNECEDOR,
            Regioes.REGIOES,
            Subcategoria.SUBCATEGORIA,
            Usuario.USUARIO,
            UsuarioFoto.USUARIO_FOTO,
            UsuarioOrganizacao.USUARIO_ORGANIZACAO,
            UsuarioPerfil.USUARIO_PERFIL,
            UsuarioRecuperarSenha.USUARIO_RECUPERAR_SENHA,
            UsuarioSubcategoria.USUARIO_SUBCATEGORIA
        );
    }
}
