/*
 * This file is generated by jOOQ.
 */
package com.dasad.empresa.jooq.model;


import com.dasad.empresa.jooq.model.tables.Categoria;
import com.dasad.empresa.jooq.model.tables.CategoriaEquipamentos;
import com.dasad.empresa.jooq.model.tables.Cidade;
import com.dasad.empresa.jooq.model.tables.Cliente;
import com.dasad.empresa.jooq.model.tables.Desconto;
import com.dasad.empresa.jooq.model.tables.Endereco;
import com.dasad.empresa.jooq.model.tables.Estado;
import com.dasad.empresa.jooq.model.tables.Estoque;
import com.dasad.empresa.jooq.model.tables.Fornecedor;
import com.dasad.empresa.jooq.model.tables.HistoricoPreco;
import com.dasad.empresa.jooq.model.tables.ItemPedido;
import com.dasad.empresa.jooq.model.tables.Organizacao;
import com.dasad.empresa.jooq.model.tables.Pais;
import com.dasad.empresa.jooq.model.tables.PasswordResetToken;
import com.dasad.empresa.jooq.model.tables.Pedido;
import com.dasad.empresa.jooq.model.tables.Perfil;
import com.dasad.empresa.jooq.model.tables.PrecosRegionais;
import com.dasad.empresa.jooq.model.tables.Produto;
import com.dasad.empresa.jooq.model.tables.ProdutoFornecedor;
import com.dasad.empresa.jooq.model.tables.Regioes;
import com.dasad.empresa.jooq.model.tables.Subcategoria;
import com.dasad.empresa.jooq.model.tables.Usuario;
import com.dasad.empresa.jooq.model.tables.UsuarioFoto;
import com.dasad.empresa.jooq.model.tables.UsuarioOrganizacao;
import com.dasad.empresa.jooq.model.tables.UsuarioPerfil;
import com.dasad.empresa.jooq.model.tables.UsuarioRecuperarSenha;
import com.dasad.empresa.jooq.model.tables.UsuarioSubcategoria;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * Tabela principal de categorias de serviços
     */
    public static final Categoria CATEGORIA = Categoria.CATEGORIA;

    /**
     * Equipamentos necessários para cada categoria de serviço
     */
    public static final CategoriaEquipamentos CATEGORIA_EQUIPAMENTOS = CategoriaEquipamentos.CATEGORIA_EQUIPAMENTOS;

    /**
     * The table <code>public.cidade</code>.
     */
    public static final Cidade CIDADE = Cidade.CIDADE;

    /**
     * The table <code>public.cliente</code>.
     */
    public static final Cliente CLIENTE = Cliente.CLIENTE;

    /**
     * The table <code>public.desconto</code>.
     */
    public static final Desconto DESCONTO = Desconto.DESCONTO;

    /**
     * The table <code>public.endereco</code>.
     */
    public static final Endereco ENDERECO = Endereco.ENDERECO;

    /**
     * The table <code>public.estado</code>.
     */
    public static final Estado ESTADO = Estado.ESTADO;

    /**
     * The table <code>public.estoque</code>.
     */
    public static final Estoque ESTOQUE = Estoque.ESTOQUE;

    /**
     * The table <code>public.fornecedor</code>.
     */
    public static final Fornecedor FORNECEDOR = Fornecedor.FORNECEDOR;

    /**
     * The table <code>public.historico_preco</code>.
     */
    public static final HistoricoPreco HISTORICO_PRECO = HistoricoPreco.HISTORICO_PRECO;

    /**
     * The table <code>public.item_pedido</code>.
     */
    public static final ItemPedido ITEM_PEDIDO = ItemPedido.ITEM_PEDIDO;

    /**
     * The table <code>public.organizacao</code>.
     */
    public static final Organizacao ORGANIZACAO = Organizacao.ORGANIZACAO;

    /**
     * The table <code>public.pais</code>.
     */
    public static final Pais PAIS = Pais.PAIS;

    /**
     * The table <code>public.password_reset_token</code>.
     */
    public static final PasswordResetToken PASSWORD_RESET_TOKEN = PasswordResetToken.PASSWORD_RESET_TOKEN;

    /**
     * The table <code>public.pedido</code>.
     */
    public static final Pedido PEDIDO = Pedido.PEDIDO;

    /**
     * The table <code>public.perfil</code>.
     */
    public static final Perfil PERFIL = Perfil.PERFIL;

    /**
     * Preços diferenciados por região para cada subcategoria
     */
    public static final PrecosRegionais PRECOS_REGIONAIS = PrecosRegionais.PRECOS_REGIONAIS;

    /**
     * The table <code>public.produto</code>.
     */
    public static final Produto PRODUTO = Produto.PRODUTO;

    /**
     * The table <code>public.produto_fornecedor</code>.
     */
    public static final ProdutoFornecedor PRODUTO_FORNECEDOR = ProdutoFornecedor.PRODUTO_FORNECEDOR;

    /**
     * Regiões de atuação dos prestadores de serviço
     */
    public static final Regioes REGIOES = Regioes.REGIOES;

    /**
     * Tabela de subcategorias de serviços vinculadas às categorias
     */
    public static final Subcategoria SUBCATEGORIA = Subcategoria.SUBCATEGORIA;

    /**
     * The table <code>public.usuario</code>.
     */
    public static final Usuario USUARIO = Usuario.USUARIO;

    /**
     * The table <code>public.usuario_foto</code>.
     */
    public static final UsuarioFoto USUARIO_FOTO = UsuarioFoto.USUARIO_FOTO;

    /**
     * The table <code>public.usuario_organizacao</code>.
     */
    public static final UsuarioOrganizacao USUARIO_ORGANIZACAO = UsuarioOrganizacao.USUARIO_ORGANIZACAO;

    /**
     * The table <code>public.usuario_perfil</code>.
     */
    public static final UsuarioPerfil USUARIO_PERFIL = UsuarioPerfil.USUARIO_PERFIL;

    /**
     * The table <code>public.usuario_recuperar_senha</code>.
     */
    public static final UsuarioRecuperarSenha USUARIO_RECUPERAR_SENHA = UsuarioRecuperarSenha.USUARIO_RECUPERAR_SENHA;

    /**
     * The table <code>public.usuario_subcategoria</code>.
     */
    public static final UsuarioSubcategoria USUARIO_SUBCATEGORIA = UsuarioSubcategoria.USUARIO_SUBCATEGORIA;
}
