/*
 * This file is generated by jOOQ.
 */
package com.dasad.empresa.jooq.model.enums;


import com.dasad.empresa.jooq.model.Public;

import org.jooq.Catalog;
import org.jooq.EnumType;
import org.jooq.Schema;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public enum StatusServico implements EnumType {

    ATIVO("ATIVO"),

    INATIVO("INATIVO"),

    SUSPENSO("SUSPENSO");

    private final String literal;

    private StatusServico(String literal) {
        this.literal = literal;
    }

    @Override
    public Catalog getCatalog() {
        return getSchema().getCatalog();
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public String getName() {
        return "status_servico";
    }

    @Override
    public String getLiteral() {
        return literal;
    }

    /**
     * Lookup a value of this EnumType by its literal. Returns
     * <code>null</code>, if no such value could be found, see {@link
     * EnumType#lookupLiteral(Class, String)}.
     */
    public static StatusServico lookupLiteral(String literal) {
        return EnumType.lookupLiteral(StatusServico.class, literal);
    }
}
